SELECT outs.ANIMAL_ID, outs.ANIMAL_TYPE, outs.NAME
FROM ANIMAL_INS as ins, ANIMAL_OUTS as outs
WHERE outs.ANIMAL_ID = ins.ANIMAL_ID AND outs.SEX_UPON_OUTCOME != ins.SEX_UPON_INTAKE 
GROUP BY outs.ANIMAL_ID