SELECT 
    RI.REST_ID, 
    RI.REST_NAME, 
    RI.FOOD_TYPE, 
    RI.FAVORITES, 
    RI.ADDRESS, 
    ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE  
FROM REST_INFO AS RI, REST_REVIEW AS RR
WHERE ADDRESS LIKE '서울%' AND RI.REST_ID = RR.REST_ID
GROUP BY RI.REST_ID
ORDER BY AVG(RR.REVIEW_SCORE) DESC, RI.FAVORITES DESC