SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT AS P, DOCTOR AS D, APPOINTMENT AS A
WHERE 
    A.APNT_CNCL_YN = 'N' AND 
    A.MCDP_CD = 'CS' AND 
    A.APNT_YMD LIKE '2022-04-13%' AND 
    A.PT_NO = P.PT_NO AND 
    A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD