WITH RECURSIVE MT_TEMP_TABLE AS (
    SELECT 0 AS h
    UNION ALL
    SELECT h+1 FROM MT_TEMP_TABLE WHERE h < 23
)

SELECT h, count(ANIMAL_ID)
FROM MT_TEMP_TABLE
    LEFT OUTER JOIN ANIMAL_OUTS
    ON HOUR(DATETIME) = MT_TEMP_TABLE.h
group by h
order by h